[workspace]
resolver = "2"
members = [
  "accessgate-smart-account",
  "account-factory/contracts/factory-contract",
  "account-factory/contracts/dummy-account",
  "account-factory/contracts/dummy-singleton",
  "accessgate-verifiers/ed25519-verifier",
  "accessgate-verifiers/p256-verifier",
  "accessgate-verifiers/secp256k1-verifier",
  "accessgate-verifiers/webauthn-verifier",
  "policies/threshold-policy",
  "policies/weighted-threshold-policy",
  "policies/session-policy",
  "policies/parameter-scoped-policy",
  "policies/spending-limit-policy",
  "policies/multi-token-spending-limit-policy",
  "policies/recipient-allowlist-policy",
  "demo/modified-ed25519-verifier",
  
  "fee-forwarder",
  "templates/timelock-vault",
  "templates/vesting-schedule",
]

[workspace.dependencies]
soroban-sdk = "26.1.0"
stellar-accounts = "=0.7.2"
stellar-contract-utils = "=0.7.2"
stellar-fee-abstraction = "=0.7.2"
stellar-access = "=0.7.2"
stellar-macros = "=0.7.2"
stellar-tokens = "=0.7.2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
