[package]
name = "timelock-vault"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
smart-account = { path = "../../accessgate-smart-account" }
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-accounts.workspace = true
